/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import javax.swing.*;
import java.awt.Component;
import java.time.LocalDate;
import java.time.Year;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark Emmanuel Asilum
 */
public class StudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentsForm
     */
    SubjectForm a = new SubjectForm();
    TeachersForm b = new TeachersForm();
    int studidcnt;
    int datenow;
    String whatsem,databasename;
    String currdate, nextdate, nowandnext;
    int eid,eidcount,studidcount;
    String filterstring = ";";
    String stdid,stdname,addr,gender,year,crs;
    static String stid,sbid, sbcod,sbdsc,sbunt,sbschd;
    String user, pass;
    String total = "select total from(select studid as x, (select sum(subUnit) from students, enroll, subjects where students.studid=enroll.studid and enroll.subId=subjects.subId and students.studid=x) as total from students)as y where x > 0";
    String useid,usenm,tmpid,tmpnm,username;
    int x=1;
    public StudentsForm() {
        initComponents();
    }
    
//    public StudentsForm(DBConnect connect){
//        this.pass = connect.pass;
//        this.user = connect.name;
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        studid = new javax.swing.JTextField();
        studname = new javax.swing.JTextField();
        studadd = new javax.swing.JTextField();
        studcrs = new javax.swing.JTextField();
        studgender = new javax.swing.JTextField();
        yrlvl = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logicOp1 = new javax.swing.JComboBox();
        filterid = new javax.swing.JTextField();
        logicOp2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filterid2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        filterid3 = new javax.swing.JTextField();
        logicOp3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filterid4 = new javax.swing.JTextField();
        filterid5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        filterid6 = new javax.swing.JTextField();
        logicOp4 = new javax.swing.JComboBox();
        logicOp5 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        filterid7 = new javax.swing.JTextField();
        logicOp6 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        filterid8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Enter Student's Name");

        studid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studidActionPerformed(evt);
            }
        });

        studname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnameActionPerformed(evt);
            }
        });

        studadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studaddActionPerformed(evt);
            }
        });

        studcrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studcrsActionPerformed(evt);
            }
        });

        studgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studgenderActionPerformed(evt);
            }
        });

        yrlvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yrlvlActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Student ID");

        jLabel3.setText("Enter Student Address");

        jLabel4.setText("Enter Student's Course");

        jLabel5.setText("Enter Student's Gender");

        jLabel6.setText("Enter Student's Year Level");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel7.setText("Student ID");

        logicOp1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=", "<>" }));
        logicOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp1ActionPerformed(evt);
            }
        });

        filterid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filteridKeyReleased(evt);
            }
        });

        logicOp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Student Name");

        jLabel9.setText("Starts");

        filterid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid2KeyReleased(evt);
            }
        });

        jLabel10.setText("Ends");

        filterid3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid3KeyReleased(evt);
            }
        });

        logicOp3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Student Address");

        jLabel12.setText("Starts");

        filterid4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid4KeyReleased(evt);
            }
        });

        filterid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterid5ActionPerformed(evt);
            }
        });
        filterid5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid5KeyReleased(evt);
            }
        });

        jLabel13.setText("Ends");

        jLabel14.setText("Student Course");

        filterid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterid6ActionPerformed(evt);
            }
        });
        filterid6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid6KeyReleased(evt);
            }
        });

        logicOp4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp4ActionPerformed(evt);
            }
        });

        logicOp5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp5ActionPerformed(evt);
            }
        });

        jLabel15.setText("Student Gender");

        filterid7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid7KeyReleased(evt);
            }
        });

        logicOp6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp6ActionPerformed(evt);
            }
        });

        jLabel16.setText("Student Year");

        filterid8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid8KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(logicOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filterid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logicOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterid2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterid3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logicOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterid4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterid5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(filterid6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterid7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterid8, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(logicOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logicOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logicOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(logicOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logicOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(filterid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(filterid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logicOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(filterid4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(filterid5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logicOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterid6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logicOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterid7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logicOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterid8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Address", "Course", "Gender", "Year", "#Units"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("Enrolled Subjects");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SubID", "SubCode", "SubDes", "SubUnits", "SubSched"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Enroll"));

        jButton4.setText("Add");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Drop");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jMenu1.setText("Window");

        jMenuItem1.setText("Subjects");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Teachers");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("New");

        jMenuItem3.setText("1st Semester");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("2nd Semester");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Summer");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studname, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studadd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studcrs, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yrlvl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studgender, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studcrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yrlvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidActionPerformed

    private void studnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnameActionPerformed

    private void studaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studaddActionPerformed

    private void studcrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studcrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studcrsActionPerformed

    private void studgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studgenderActionPerformed

    private void yrlvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrlvlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yrlvlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        students stud = new students();
        stud.AddStud(Integer.parseInt(studid.getText()), studname.getText(), studadd.getText(), studcrs.getText(), studgender.getText(), yrlvl.getText());
        ShowStudRec();
        stud.createUserStud(studid.getText(), studname.getText());
        stud.grantPriv(LoginForm.database,studid.getText(), studname.getText());
    }//GEN-LAST:event_jButton1ActionPerformed
    private void ShowStudRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        tblmodel.setRowCount(0);
        
        //show tables when texfields are blank
        if(filterid.getText().equals("")||filterid2.getText().equals("")||filterid3.getText().equals("")||filterid4.getText().equals("")||
           filterid5.getText().equals("")||filterid6.getText().equals("")||filterid7.getText().equals("")||filterid8.getText().equals("")){
            filterstring = ";";
        }
        
        //filter for student id
        if(!filterid.getText().equals("")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText();
        }

        //filter for start of name
        if(!filterid2.getText().equals("")){
            filterstring = " where studname like '"+filterid2.getText()+"%'";
        }

        //filter for end of name
         if(!filterid3.getText().equals("")){
            filterstring = " where studname like '%"+filterid3.getText()+"'";
        }

        //if and ang operator and sa textfield 2
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"
                            +filterid2.getText()+"%'";
        }

        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"
                            +filterid2.getText()+"%'";
        }
        //if and ang operator and sa textfield 2
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '%"
                            +filterid3.getText()+"'";
        }

        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '%"
                            +filterid3.getText()+"'";
        }

        //and and or for text field 3
        if(!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where studname like '"+filterid2.getText()+"%'"+" or studname like '%"+filterid3.getText()+"'";
        }

        if(!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where studname like '"+filterid2.getText()+"%'"+" and studname like '%"+filterid3.getText()+"'";
        }


        //if and ang operator and sa textfield 2
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
           &&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"
                   +filterid2.getText()+"%'"+" or studname like '%"+filterid3.getText()+"'";
        }

        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
            &&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"
                            +filterid2.getText()+"%'"+" and studname like '%"+filterid3.getText()+"'";
        }

        //filter for start of address
        if(!filterid4.getText().equals("")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'";
        }
        //filter for start of address and id
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '"
                            +filterid4.getText()+"%'";
        }
         if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"
                            +filterid4.getText()+"%'";
        }

        //filter for end of address
         if(!filterid5.getText().equals("")){
            filterstring = " where studadd like '%"+filterid5.getText()+"'";
        }
        //end of address and id
         if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '%"
                            +filterid5.getText()+"'";
        }
         if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '%"
                            +filterid5.getText()+"'";
        }
         if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
            &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"
                            +filterid4.getText()+"%'"+" and studadd like '%"+filterid5.getText()+"'";
        }


        //address with logical operator 3
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" and studadd like '%"+filterid5.getText()+"'";
        }
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" or studadd like '%"+filterid5.getText()+"'";
        }

        //filter for name and address
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid2.getText().equals("")
           &&!filterid3.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
           filterstring = " where studadd like '"+filterid4.getText()+"%'"+" or studadd like '%"+filterid5.getText()+"'"
                            +" or studname like '"+filterid2.getText()+"%'"+" or studname like '%"+filterid3.getText()+"'";
        }

        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid2.getText().equals("")
           &&!filterid3.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
           
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" or studadd like '%"
                            +filterid5.getText()+"'"+" and studname like '"+filterid2.getText()+"%'"
                            +" and studname like '%"+filterid3.getText()+"'";
        }
        
        
        //start of name and start address
        if(!filterid2.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" and studadd like '"+filterid4.getText()+"%'";
        }
        if(!filterid2.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" or studadd like '"+filterid4.getText()+"%'";
        }
        //start of name and start address with id
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"
                            +filterid2.getText()+"%'"+" and studadd like '"+filterid4.getText()+"%'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"
                            +filterid2.getText()+"%'"+" or studadd like '"+filterid4.getText()+"%'";
        }
        //start name end of address with id
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid5.getText().equals("")
                &&logicOp3.getSelectedItem().equals("AND")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                           +" and studadd like '%"+filterid5.getText()+"'";
        }
        
        
        //end of name and start of address
        if(!filterid3.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" and studadd like '"+filterid4.getText()+"%'";
        }
        if(!filterid3.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" or studadd like '"+filterid4.getText()+"%'";
        }
        
         //end of name and start of address with id
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '%"
                            +filterid3.getText()+"'"+" and studadd like '"+filterid4.getText()+"%'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '%"
                            +filterid3.getText()+"'"+" or studadd like '"+filterid4.getText()+"%'";
        }
        
        
        //end of name and end address
        if(!filterid3.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" and studadd like '%"+filterid5.getText()+"'";
        }
        if(!filterid3.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" or studadd like '%"+filterid5.getText()+"'";
        }
        //end of name and end address with id
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '%"
                            +filterid3.getText()+"'"+" and studadd like '%"+filterid5.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '%"+filterid3.getText()+
                            "'"+" or studadd like '%"+filterid5.getText()+"'";
        }
        
        //end of address and start of name
        if(!filterid2.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" and studadd like '%"+filterid5.getText()+"'";
        }
        if(!filterid2.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" or studadd like '%"+filterid5.getText()+"'";
        }
       
        //if naa studid, name, and address
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
            &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")
            &&logicOp3.getSelectedItem().equals("OR")){
           
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"
                   +filterid2.getText()+"%'"+" or studname like '%"+filterid3.getText()+"'"+" or studadd like '"
                   +filterid4.getText()+"%'"+" or studadd like '%"+filterid5.getText();
        }

        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
           &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
           &&logicOp3.getSelectedItem().equals("AND")){
           
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"
                            +filterid2.getText()+"%'"+" and studname like '%"+filterid3.getText()+"'"+" and studadd like '"
                            +filterid4.getText()+"%'"+" and studadd like '%"+filterid5.getText();
        }

         //student id and address
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '"
                            +filterid4.getText()+"%'"+" or studadd like '%"+filterid5.getText()+"'";
        }

        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"
                           +filterid4.getText()+"%'"+" and studadd like '%"+filterid5.getText()+"'";
        }

        //filter for course
        if(!filterid6.getText().equals("")){
            filterstring = " where studcrs = '"+filterid6.getText()+"'";
        }

        //filter for id and course
        if(!filterid.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studcrs = '"
                            +filterid6.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studcrs like '"+filterid6.getText()+"'";
        }
        
       
        //name and course
        if(!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" and studcrs like '"+filterid6.getText()+"'";
        }
        if(!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" and studcrs like '"+filterid6.getText()+"'";
        }
         if(!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" or studcrs like '"+filterid6.getText()+"'";
        }
         if(!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" or studcrs like '"+filterid6.getText()+"'";
        }

         //filter for address and course
        if(!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" and studcrs like '"+filterid6.getText()+"'";
        }
        if(!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studadd like '%"+filterid5.getText()+"'"+" and studcrs like '"+filterid6.getText()+"'";
        }
         if(!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" or studcrs like '"+filterid6.getText()+"'";
        }
         if(!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where studadd like '%"+filterid5.getText()+"'"+" or studcrs like '"+filterid6.getText()+"'";
        }
        //filter for id, course, start name 
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" and studname like '"+filterid2.getText()+"%'"
                            +" and  studid " + logicOp1.getSelectedItem() + filterid.getText();
        }
        //filter for id, course and end name
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" and studname like '%"+filterid3.getText()+"'"
                            +" and  studid " + logicOp1.getSelectedItem() + filterid.getText();
        }
        
        //filter for id course star name end name
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                    +"and studname like '%"+filterid3.getText()+"'"+" and studcrs like '" +filterid6.getText()+"'";
        }
        
        //filter for id, course, and start address
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" and studadd like '"+filterid4.getText()+"%'"
                            +" and  studid " + logicOp1.getSelectedItem() + filterid.getText();
        }
        //filter for id, course, and end address
        if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" and studadd like '%"+filterid5.getText()+"'"
                            +" and  studid " + logicOp1.getSelectedItem() + filterid.getText();
        }
        //filter for id, course, start and end address
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"+filterid4.getText()+"%'"
                    +"and studadd like '%"+filterid5.getText()+"'"+" and studcrs like '" +filterid6.getText()+"'";
        }
       
       //filter for gender
       if(!filterid7.getText().equals("")){
            filterstring = " where studgender = '"+filterid7.getText()+"'";
        }
       
       //filter for id and gender
       if(!filterid.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studgender like '"
                            +filterid7.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studgender like '"
                            +filterid7.getText()+"'";
        }
       //name and gender
     
       //start name
       if(!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" and studgender like '"+filterid7.getText()+"'";
        }
       if(!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //end name
       if(!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" and studgender like '"+filterid7.getText()+"'";
        }
         
         if(!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //adress and gender
       //start address
       if(!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" and studgender like '"+filterid7.getText()+"'";
        }
       if(!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //end address
       if(!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studadd like '%"+filterid5.getText()+"'"+" and studgender like '"+filterid7.getText()+"'";
        }
         
        if(!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studadd like '%"+filterid5.getText()+"'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //course and gender
       if(!filterid6.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" and studgender like '"+filterid7.getText()+"'";
        }
       if(!filterid6.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //id, gender start name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                           +" and studgender like '"+filterid7.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid2.getText()+"%'"
                           +" or studgender like '"+filterid7.getText()+"'";
        }
       //id, gender end name
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid3.getText()+"%'"
                           +" and studgender like '"+filterid7.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid3.getText()+"%'"
                           +" or studgender like '"+filterid7.getText()+"'";
        }
       //id, gender, start name, and name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                           +" and studname like '"+filterid3.getText()+"%'"+" and studgender like '"+filterid7.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid2.getText()+"%'"
                           +" or studname like '"+filterid3.getText()+"%'"
                           +" or studgender like '"+filterid7.getText()+"'";
        }
       //id, gender, start address
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"+filterid4.getText()+
                            "%'"+" and studgender like '"+filterid7.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '"+filterid4.getText()+
                            "%'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //id, gender, end address
       if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '%"+filterid5.getText()+"'"
                           +" and studgender like '"+filterid7.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '%"+filterid5.getText()+
                            "'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //id. gender, start and end address
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"+filterid4.getText()+" and studadd like '%"+filterid5.getText()+"'"
                           +" and studgender like '"+filterid7.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '"+filterid4.getText()+" or studadd like '%"+filterid5.getText()+
                            "'"+" or studgender like '"+filterid7.getText()+"'";
        }
       //id, start name, end name, start adress,end address, course, gender
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                           +" and studname like '"+filterid3.getText()+"%'"+" and studadd like '"+filterid4.getText()
                           +" and studadd like '%"+filterid5.getText()+"'"+" and studcrs like '"+filterid6.getText()
                           +" and studgender like '"+filterid7.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid2.getText()+"%'"
                           +" or studname like '"+filterid3.getText()+"%'"+" or studadd like '"+filterid4.getText()
                           +" or studadd like '%"+filterid5.getText()+"'"+" or studcrs like '"+filterid6.getText()
                           +" or studgender like '"+filterid7.getText()+"'";
        }
        
        //YEAR LEVEL
        
       //filter for year
        
       if(!filterid8.getText().equals("")){
            filterstring = " where yrlvl = '"+ filterid8.getText()+"'";
        }
       
       //filter for id and year
       if(!filterid.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and yrlvl like '"
                            +filterid8.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or yrlvl like '"
                            +filterid8.getText()+"'";
        }
       //name and year
     
       //start name
       if(!filterid2.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" and yrlvl like '"+filterid8.getText()+"'";
        }
       if(!filterid2.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studname like '"+filterid2.getText()+"%'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //end name
       if(!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" and yrlvl like '"+filterid8.getText()+"'";
        }
         
         if(!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studname like '%"+filterid3.getText()+"'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //adress and year
       //start address
       if(!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" and yrlvl like '"+filterid8.getText()+"'";
        }
       if(!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studadd like '"+filterid4.getText()+"%'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //end address
       if(!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studadd like '%"+filterid5.getText()+"'"+" and yrlvl like '"+filterid8.getText()+"'";
        }
         
        if(!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studadd like '%"+filterid5.getText()+"'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //course and year
       if(!filterid6.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" and yrlvl like '"+filterid8.getText()+"'";
        }
       if(!filterid6.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studcrs like '"+filterid6.getText()+"'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //id, year start name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid8.getText().equals("")
          &&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                           +" and yrlvl like '"+filterid8.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid2.getText()+"%'"
                           +" or yrlvl like '"+filterid8.getText()+"'";
        }
       //id, year end name
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")
          &&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid3.getText()+"%'"
                           +" and yrlvl like '"+filterid8.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid3.getText()+"%'"
                           +" or yrlvl like '"+filterid8.getText()+"'";
        }
       //id, year, start name, and name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")
          &&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                           +" and studname like '"+filterid3.getText()+"%'"+" and yrlvl like '"+filterid8.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid2.getText()+"%'"
                           +" or studname like '"+filterid3.getText()+"%'"
                           +" or yrlvl like '"+filterid8.getText()+"'";
        }
       //id, year, start address
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"+filterid4.getText()+
                            "%'"+" and yrlvl like '"+filterid8.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '"+filterid4.getText()+
                            "%'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //id, year, end address
       if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '%"+filterid5.getText()+"'"
                           +" and yrlvl like '"+filterid8.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '%"+filterid5.getText()+
                            "'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //id. year, start and end address
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studadd like '"+filterid4.getText()+"%'"+" and studadd like '%"+filterid5.getText()+"'"
                           +" and yrlvl like '"+filterid8.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studadd like '"+filterid4.getText()+"%'"+" or studadd like '%"+filterid5.getText()+
                            "'"+" or yrlvl like '"+filterid8.getText()+"'";
        }
       //id, start name, end name, start adress,end address, course, year
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" and studname like '"+filterid2.getText()+"%'"
                           +" and studname like '"+filterid3.getText()+"%'"+" and studadd like '"+filterid4.getText()
                           +"%'"+" and studadd like '%"+filterid5.getText()+"'"+" and studcrs like '"+filterid6.getText()
                           +" and yrlvl like '"+filterid8.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where studid " + logicOp1.getSelectedItem() + filterid.getText()+" or studname like '"+filterid2.getText()+"%'"
                           +" or studname like '"+filterid3.getText()+"%'"+" or studadd like '"+filterid4.getText()+"%'"+" or studadd like '%"+filterid5.getText()+"'"+" or studcrs like '"+filterid6.getText()+" or yrlvl like '"+filterid8.getText()+"'";
        }
       
        //year and gender
        if(!filterid8.getText().equals("")&&!filterid7.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where yrlvl like '"+ filterid8.getText()+"'"+" and studgender like '"+filterid7.getText()+"'";
        }
        if(!filterid8.getText().equals("")&&!filterid7.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where yrlvl like '"+ filterid8.getText()+"'"+" or studgender like '"+filterid7.getText()+"'";
        }
        //year and course
       if(!filterid8.getText().equals("")&&!filterid6.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where yrlvl like '"+ filterid8.getText()+"'"+" and studcrs like '"+filterid6.getText()+"'";
        }
        if(!filterid8.getText().equals("")&&!filterid6.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where yrlvl like '"+ filterid8.getText()+"'"+" or studcrs like '"+filterid6.getText()+"'";
        }
       //unitssss
        DBConnect a = new DBConnect(LoginForm.loguser, LoginForm.logpass,LoginForm.database){
            
        };
        try
        {   
            String query = "select * from students" + filterstring;
            a.rs = a.st.executeQuery(query);
            //String query2 = "select total from(select studid as x, (select sum(subUnit) from students, enroll, subjects where students.studid=enroll.studid and enroll.subId=subjects.subId and students.studid=x) as total from students)as y where x > 0";
            //a.rs = a.st.executeQuery(query2);    
                    while(a.rs.next())
                    {
                        String id = a.rs.getString("studid");
                        String name = a.rs.getString("studname"); 
                        String addr = a.rs.getString("studadd"); 
                        String course = a.rs.getString("studcrs"); 
                        String gender = a.rs.getString("studgender"); 
                        String yearlevel = a.rs.getString("yrlvl");
                        String totUnits = a.rs.getString("totUnits");
                        String[] item = {id,name,addr,course,gender,yearlevel,totUnits};
                        tblmodel.addRow(item);

                    }
            /*String query2 = "select total from(select studid as x, (select sum(subUnit) from students, enroll, subjects where students.studid=enroll.studid and enroll.subId=subjects.subId and students.studid=x) as total from students)as y where x > 0";
            a.rs = a.st.executeQuery(query2);
                    while(a.rs.next()){
                        String totUnits = a.rs.getString("total");
                        String[] item = {totUnits};
                        tblmodel.addRow(item);
                    }*/
                    
        }catch(Exception ex)
        {
            System.out.println("failed select query "+ex);
        }
    }
    
    private void ShowEnrollRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable2.getModel();
        tblmodel.setRowCount(0);
        
        DBConnect a = new DBConnect(LoginForm.loguser, LoginForm.logpass,LoginForm.database);
        try
        {
            
            String query = "select subjects.subId, subCode, subDes, subUnit, subSched from students, enroll, subjects where students.studid="+stid+" and students.studid=enroll.studid and enroll.subId=subjects.subId";
            
            a.rs = a.st.executeQuery(query);
                    while(a.rs.next())
                    {
                        String i = a.rs.getString("subId");
                        String c = a.rs.getString("subCode"); 
                        String d = a.rs.getString("subDes"); 
                        String u = a.rs.getString("subUnit"); 
                        String s = a.rs.getString("subSched"); 
                    
                        String[] item = {i,c,d,u,s};
                        tblmodel.addRow(item);

                    }
        }catch(Exception ex)
        {
            System.out.println("Show Enroll records failed"+ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        students stud = new students();
        
        if(studid.getText().isEmpty()&& studname.getText().isEmpty()){
            dropEmp();
            stud.DelStud(filterstring);
        }
        else{
            stud.dropStud(studid.getText(), studname.getText());
            stud.DelStud(filterstring);
        }
        ShowStudRec();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void dropEmp(){
        DBConnect a = new DBConnect(LoginForm.loguser, LoginForm.logpass,LoginForm.database);
        String query1 = "select count(studid) from students";
        try{
            a.rs = a.st.executeQuery(query1);
            a.rs.next();
            studidcnt=a.rs.getInt(1);
        }catch(Exception ex){
            System.out.print("Failed to insert"+ex);
        }
        
        try{
            while(studidcnt != 0){
                String query2 = "select studid from students where studid="+x;
                  
                a.rs = a.st.executeQuery(query2);
                while(a.rs.next()){
                    tmpid = a.rs.getString("studid");
                    useid=tmpid;
                }
                String query5 = "select studname from students where studid="+x;
                a.rs = a.st.executeQuery(query5);
                while(a.rs.next()){
                    tmpnm = a.rs.getString("studname");
                    usenm=tmpnm;
                }                    
                username=useid+usenm;
                String query3 = "drop user '"+username+"'@'localhost'";   
                a.st.executeUpdate(query3);                                                          
                studidcnt=studidcnt-1;
                x=x+1;                    
            }
      
            }catch(Exception ex){
                System.out.print("Failed to insert"+ex);
            } 
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        students stud = new students();
         stud.EditStud(studname.getText(), studadd.getText(), studcrs.getText(), studgender.getText(),yrlvl.getText(),filterstring);
        //stud.EditStud(Integer.parseInt(studid.getText()), studname.getText(), studadd.getText(), studcrs.getText(), studgender.getText(),yrlvl.getText());
        ShowStudRec();
        //, studname.getText(), studadd.getText(), studcrs.getText(), studgender.getText(), yrlvl.getText()
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        b.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void filterid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterid5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterid5ActionPerformed

    private void filterid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterid6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterid6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       ShowStudRec();
       ShowDate();
       
    }//GEN-LAST:event_formWindowOpened

    private void filteridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filteridKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filteridKeyReleased

    private void filterid2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid2KeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filterid2KeyReleased

    private void filterid3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid3KeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filterid3KeyReleased

    private void filterid4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid4KeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filterid4KeyReleased

    private void filterid5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid5KeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filterid5KeyReleased

    private void filterid6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid6KeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filterid6KeyReleased

    private void logicOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp4ActionPerformed
         ShowStudRec();
    }//GEN-LAST:event_logicOp4ActionPerformed

    private void filterid7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid7KeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filterid7KeyReleased

    private void filterid8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid8KeyReleased
        ShowStudRec();
    }//GEN-LAST:event_filterid8KeyReleased

    private void logicOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp1ActionPerformed
         ShowStudRec();
    }//GEN-LAST:event_logicOp1ActionPerformed

    private void logicOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp3ActionPerformed
         ShowStudRec();
    }//GEN-LAST:event_logicOp3ActionPerformed

    private void logicOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp5ActionPerformed
        ShowStudRec();
    }//GEN-LAST:event_logicOp5ActionPerformed

    private void logicOp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp6ActionPerformed
         ShowStudRec();
    }//GEN-LAST:event_logicOp6ActionPerformed

    private void logicOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp2ActionPerformed
         ShowStudRec();
    }//GEN-LAST:event_logicOp2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       StudentsForm a = new StudentsForm();
       int[] selectRow = jTable1.getSelectedRows();
       stid=(String) jTable1.getValueAt(selectRow[0], 0);
       studid.setText(stid);
       stdname=(String) jTable1.getValueAt(selectRow[0], 1);
       studname.setText(stdname);
       addr=(String) jTable1.getValueAt(selectRow[0], 2);
       studadd.setText(addr);
       crs=(String) jTable1.getValueAt(selectRow[0], 3);
       studcrs.setText(crs);
       gender=(String) jTable1.getValueAt(selectRow[0], 4);
       studgender.setText(gender);
       year=(String) jTable1.getValueAt(selectRow[0], 5);
       yrlvl.setText(year);
       ShowEnrollRec();
      
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        a.setVisible(false);
        b.setVisible(false);
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int i = okcancel("Drop SubjectID:"+sbid+" from studentID: "+stid);
        if(i==0){
            enroll e = new enroll();
            e.DropSub(Integer.parseInt(stid), Integer.parseInt(sbid), eid);
            ShowEnrollRec();
            e.UpdateUnits(Integer.parseInt(stid));
            e.UpdateEnrolledStud(Integer.parseInt(sbid));
            ShowStudRec();
            JOptionPane.showMessageDialog(this,"Dropped!!!");
           
            
           
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i = okcancel("Enroll SubjectID:"+sbid+" to studentID: "+stid);
        DBConnect a = new DBConnect(LoginForm.loguser, LoginForm.logpass,LoginForm.database);

        String query = "select max(eid) from enroll";
        try{
            a.rs = a.st.executeQuery(query);
            a.rs.next();
            eidcount=a.rs.getInt(1);
            eid=eidcount+1;
        }catch(Exception ex){
            System.out.print("Failed to insert "+ex);
        }
        if(i==0){
            enroll e = new enroll();
            e.EnrollStud(eid,Integer.parseInt(stid), Integer.parseInt(sbid));
            ShowEnrollRec();
            e.UpdateUnits(Integer.parseInt(stid));
            e.UpdateEnrolledStud(Integer.parseInt(sbid));
            ShowStudRec();
            JOptionPane.showMessageDialog(this,"Enrolled!!!");
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked
    private void ShowDate(){
        LocalDate now = LocalDate.now();
        LocalDate next = now.plusYears(1);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy");
        currdate= now.format(formatter);
        nextdate=next.format(formatter);
        nowandnext = currdate+"_"+nextdate;
        
       
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ShowDate();
        whatsem="1st_sy";
        databasename=whatsem+nowandnext;
        newdatabase name = new newdatabase();
        name.createdatabase(databasename);
        createTables();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ShowDate();
        whatsem="2nd_sy";
        databasename=whatsem+nowandnext;
        newdatabase name = new newdatabase();
        name.createdatabase(databasename);
        createTables();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ShowDate();
        whatsem="Summer_sy";
        databasename=whatsem+nowandnext;
        newdatabase name = new newdatabase();
        name.createdatabase(databasename);
        createTables();
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    private void createTables(){
        String query1 ="use "+databasename;
        String query2 ="create table students(studid int, studname text, studadd text, studcrs text, studgender text,yrlvl text, totUnits int, primary key(studid))";
        String query3 ="create table subjects(subId int, subCode text, subDes text, subUnit int, subSched text,numOfStud int, primary key(subId))";
        String query4 ="create table teachers(teachId int, teachName text, teachDept text, teachAddr text, teachCont int,teachStat text, assSub int, primary key(teachId))";
        String query5 ="create table enroll(eid int, studid int, subId int, primary key(eid), foreign key(studid) references students(studid) on delete cascade, foreign key(subId) references subjects(subId) on delete cascade)";
        String query6 ="create table assign(teachId int, subId int, dateAss text, primary key(subId), foreign key(teachId) references teachers(teachId) on delete cascade, foreign key(subId) references subjects(subId) on delete cascade)";
        String query7 ="create table grades(gradeId int, prelim text, midterm text, prefinal text, final text, primary key(gradeId))";
        String query8 ="create table transCharg(transId int, transDept float(15, 2), transUnit float(15, 2), transInsur float(15, 2), transComp float(15, 2), transLab float(15,2), transCult float(15, 2), transLib float(15, 2), primary key (transId))";
        String query9 ="create table invoice (invDate text, studid int, transId int, primary key(studid), foreign key(studid) references students(studid) on delete cascade, foreign key(transId) references transCharg(transId) on delete cascade)";
        
        DBConnect a = new DBConnect(LoginForm.loguser, LoginForm.logpass,LoginForm.database);
        try{
            a.st.executeQuery(query1);
            a.st.executeUpdate(query2);
            a.st.executeUpdate(query3);
            a.st.executeUpdate(query4);
            a.st.executeUpdate(query5);
            a.st.executeUpdate(query6);
            a.st.executeUpdate(query7);
            a.st.executeUpdate(query8);
            a.st.executeUpdate(query9);
            
            
        }catch(Exception ex){
            System.out.print("Failed to create tables"+ex);
        }
    }
    
    public static int okcancel(String theMessage){
       int result = JOptionPane.showConfirmDialog((Component) null, theMessage,
        "alert", JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filterid;
    private javax.swing.JTextField filterid2;
    private javax.swing.JTextField filterid3;
    private javax.swing.JTextField filterid4;
    private javax.swing.JTextField filterid5;
    private javax.swing.JTextField filterid6;
    private javax.swing.JTextField filterid7;
    private javax.swing.JTextField filterid8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox logicOp1;
    private javax.swing.JComboBox logicOp2;
    private javax.swing.JComboBox logicOp3;
    private javax.swing.JComboBox logicOp4;
    private javax.swing.JComboBox logicOp5;
    private javax.swing.JComboBox logicOp6;
    private javax.swing.JTextField studadd;
    private javax.swing.JTextField studcrs;
    private javax.swing.JTextField studgender;
    private javax.swing.JTextField studid;
    private javax.swing.JTextField studname;
    private javax.swing.JTextField yrlvl;
    // End of variables declaration//GEN-END:variables

   

    
}
