/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import static enrollmentsystem.StudentsForm.stid;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark Emmanuel Asilum
 */
public class SubjectForm extends javax.swing.JFrame {

    /**
     * Creates new form SubjectForm
     */
    //TeachersForm a = new TeachersForm();
    String filterstring = ";";
    static String sbId, sbCod, sbDsc, sbUnt, sbSchd;
    public SubjectForm() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        subId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        subCode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        subDes = new javax.swing.JTextField();
        subUnit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        subSched = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filterid1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filterid2 = new javax.swing.JTextField();
        filterid3 = new javax.swing.JTextField();
        filterid4 = new javax.swing.JTextField();
        filterid7 = new javax.swing.JTextField();
        logicOp1 = new javax.swing.JComboBox();
        logicOp2 = new javax.swing.JComboBox();
        logicOp3 = new javax.swing.JComboBox();
        logicOp4 = new javax.swing.JComboBox();
        logicOp = new javax.swing.JComboBox();
        logicOp5 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filterid5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        filterid6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setText("Enter Subject ID");

        subId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subIdActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Code");

        subCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCodeActionPerformed(evt);
            }
        });

        jLabel9.setText("Enter Desc");

        subDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subDesActionPerformed(evt);
            }
        });

        subUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subUnitActionPerformed(evt);
            }
        });

        jLabel10.setText("Enter Units");

        jLabel11.setText("Enter Sched");

        subSched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSchedActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Subject Code", "Description", "Units", "Schedule", "Enrolled"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel1.setText("Subject ID");

        filterid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid1KeyReleased(evt);
            }
        });

        jLabel2.setText("Subject Code");

        jLabel3.setText("Description");

        jLabel4.setText("Units");

        jLabel5.setText("Schedule");

        filterid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid2KeyReleased(evt);
            }
        });

        filterid3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid3KeyReleased(evt);
            }
        });

        filterid4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid4KeyReleased(evt);
            }
        });

        filterid7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid7KeyReleased(evt);
            }
        });

        logicOp1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp1ActionPerformed(evt);
            }
        });

        logicOp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp2ActionPerformed(evt);
            }
        });

        logicOp3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp3ActionPerformed(evt);
            }
        });

        logicOp4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp4ActionPerformed(evt);
            }
        });

        logicOp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=", "<>" }));
        logicOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOpActionPerformed(evt);
            }
        });

        logicOp5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=", "<>" }));
        logicOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Start");

        jLabel12.setText("End");

        filterid5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid5KeyReleased(evt);
            }
        });

        jLabel13.setText("Start");

        jLabel14.setText("End");

        filterid6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logicOp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterid1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logicOp5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filterid6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logicOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logicOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(23, 23, 23)
                                .addComponent(filterid7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logicOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logicOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(filterid4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(filterid5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(filterid2)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filterid3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGap(49, 49, 49)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filterid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logicOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logicOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logicOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterid5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterid4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logicOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(logicOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterid6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logicOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(filterid7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Course", "Gender", "Year"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("Class List");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subSched, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subDes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subCode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(subId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(197, 197, 197)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(subId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(subCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(subDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(subUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(subSched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subIdActionPerformed

    private void subCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subCodeActionPerformed

    private void subDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subDesActionPerformed

    private void subUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subUnitActionPerformed

    private void subSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSchedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subSchedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        subjects sub = new subjects();
        sub.AddSub(Integer.parseInt(subId.getText()), Integer.parseInt(subCode.getText()), subDes.getText(), Integer.parseInt(subUnit.getText()),  subSched.getText());
        ShowSubRec();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ShowSubRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        tblmodel.setRowCount(0);
        
        if(filterid1.getText().equals("")&&filterid2.getText().equals("")&&filterid2.getText().equals("")){
            filterstring = ";";
        }
        
        if(!filterid1.getText().equals("")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText();
        }
        
        //subcode start
         
        //start code
        if(!filterid2.getText().equals("")){
            filterstring = " where subCode like '" +filterid2.getText()+"%'";
        }
        
        //end code
        if(!filterid3.getText().equals("")){
            filterstring = " where subCode like '%" +filterid3.getText()+"'";
        }
        //
        
        //if and ang operator and sa textfield 2
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&logicOp1.getSelectedItem().equals("OR")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"
                            +filterid2.getText()+"%'";
        }

        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&logicOp1.getSelectedItem().equals("AND")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"
                            +filterid2.getText()+"%'";
        }
        //if and ang operator and sa textfield 2
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&logicOp1.getSelectedItem().equals("OR")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '%"
                            +filterid3.getText()+"'";
        }

        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&logicOp1.getSelectedItem().equals("AND")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '%"
                            +filterid3.getText()+"'";
        }

        //and and or for text field 3
        if(!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&logicOp1.getSelectedItem().equals("OR")){
           filterstring = " where subCode like '"+filterid2.getText()+"%'"+" or subCode like '%"+filterid3.getText()+"'";
        }

        if(!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&logicOp1.getSelectedItem().equals("AND")){
           filterstring = " where subCode like '"+filterid2.getText()+"%'"+" and subCode like '%"+filterid3.getText()+"'";
        }


        //if and ang operator and sa textfield 2
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
           &&logicOp1.getSelectedItem().equals("OR")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"
                   +filterid2.getText()+"%'"+" or subCode like '%"+filterid3.getText()+"'";
        }

        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
            &&logicOp1.getSelectedItem().equals("AND")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"
                            +filterid2.getText()+"%'"+" and subCode like '%"+filterid3.getText()+"'";
        }
        
        

        //filter for description
        //////////////////////////////////
        
        //filter for start of description
        if(!filterid4.getText().equals("")){
            filterstring = " where subDes like '"+filterid4.getText()+"%'";
        }
        //filter for start of description and id
        if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subDes like '"
                            +filterid4.getText()+"%'";
        }
         if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '"
                            +filterid4.getText()+"%'";
        }

        //filter for end of description
         if(!filterid7.getText().equals("")){
            filterstring = " where subDes like '%"+filterid5.getText()+"'";
        }
        //end of description and id
         if(!filterid1.getText().equals("")&&!filterid7.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subDes like '%"
                            +filterid5.getText()+"'";
        }
         if(!filterid1.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '%"
                            +filterid5.getText()+"'";
        }
         if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
            &&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '"
                            +filterid4.getText()+"%'"+" and subDes like '%"+filterid5.getText()+"'";
        }


        //description with logical operator 3
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subDes like '"+filterid4.getText()+"%'"+" and subDes like '%"+filterid5.getText()+"'";
        }
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subDes like '"+filterid4.getText()+"%'"+" or subDes like '%"+filterid5.getText()+"'";
        }

        //filter for code and description
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid2.getText().equals("")
           &&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where subDes like '"+filterid4.getText()+"%'"+" or subDes like '%"+filterid5.getText()+"'"
                            +" or subCode like '"+filterid2.getText()+"%'"+" or subCode like '%"+filterid3.getText()+"'";
        }

        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid2.getText().equals("")
           &&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
           
            filterstring = " where subDes like '"+filterid4.getText()+"%'"+" or subDes like '%"
                            +filterid5.getText()+"'"+" and subCode like '"+filterid2.getText()+"%'"
                            +" and subCode like '%"+filterid3.getText()+"'";
        }
        
        
        //start of code and start description
        if(!filterid2.getText().equals("")&&!filterid4.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" and subDes like '"+filterid4.getText()+"%'";
        }
        if(!filterid2.getText().equals("")&&!filterid4.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" or subDes like '"+filterid4.getText()+"%'";
        }
        //start of code and start description with id
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"
                            +filterid2.getText()+"%'"+" and subDes like '"+filterid4.getText()+"%'";
        }
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"
                            +filterid2.getText()+"%'"+" or subDes like '"+filterid4.getText()+"%'";
        }
        //start code end of description with id
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid5.getText().equals("")
                &&logicOp2.getSelectedItem().equals("AND")&&logicOp1.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"+filterid2.getText()+"%'"
                           +" and subDes like '%"+filterid5.getText()+"'";
        }
        
        
        //end of code and start of description
        if(!filterid3.getText().equals("")&&!filterid4.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" and subDes like '"+filterid4.getText()+"%'";
        }
        if(!filterid3.getText().equals("")&&!filterid4.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" or subDes like '"+filterid4.getText()+"%'";
        }
        
         //end of code and start of description with id
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '%"
                            +filterid3.getText()+"'"+" and subDes like '"+filterid4.getText()+"%'";
        }
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '%"
                            +filterid3.getText()+"'"+" or subDes like '"+filterid4.getText()+"%'";
        }
        
        
        //end of code and end description
        if(!filterid3.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" and subDes like '%"+filterid5.getText()+"'";
        }
        if(!filterid3.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" or subDes like '%"+filterid5.getText()+"'";
        }
        //end of code and end description with id
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '%"
                            +filterid3.getText()+"'"+" and subDes like '%"+filterid5.getText()+"'";
        }
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '%"+filterid3.getText()+
                            "'"+" or subDes like '%"+filterid5.getText()+"'";
        }
        
        //end of description and start of code
        if(!filterid2.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" and subDes like '%"+filterid5.getText()+"'";
        }
        if(!filterid2.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" or subDes like '%"+filterid5.getText()+"'";
        }
       
        //if naa subId, code, and description
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
            &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp1.getSelectedItem().equals("OR")
            &&logicOp2.getSelectedItem().equals("OR")){
           
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"
                   +filterid2.getText()+"%'"+" or subCode like '%"+filterid3.getText()+"'"+" or subDes like '"
                   +filterid4.getText()+"%'"+" or subDes like '%"+filterid5.getText();
        }

        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
           &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp1.getSelectedItem().equals("AND")
           &&logicOp2.getSelectedItem().equals("AND")){
           
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"
                            +filterid2.getText()+"%'"+" and subCode like '%"+filterid3.getText()+"'"+" and subDes like '"
                            +filterid4.getText()+"%'"+" and subDes like '%"+filterid5.getText();
        }

         //subid  and description
        if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subDes like '"
                            +filterid4.getText()+"%'"+" or subDes like '%"+filterid5.getText()+"'";
        }

        if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '"
                           +filterid4.getText()+"%'"+" and subDes like '%"+filterid5.getText()+"'";
        }
        
        
        ////////////////////////////////
       
        //filter for units
        if(!filterid6.getText().equals("")){
            filterstring = " where subUnit " + logicOp5.getSelectedItem() + filterid6.getText();
        }
        

        //filter for id and units
        if(!filterid1.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subUnit "
                            + logicOp5.getSelectedItem() + filterid6.getText();
        }
        if(!filterid1.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
        
       
        //code and units
        if(!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" and subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
        if(!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" and subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
         if(!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" or subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
         if(!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" or subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }

         //filter for description and units
        if(!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subDes like '"+filterid4.getText()+"%'"+" and subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
        if(!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subDes like '%"+filterid5.getText()+"'"+" and subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
         if(!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where subDes like '"+filterid4.getText()+"%'"+" or subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
         if(!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where subDes like '%"+filterid5.getText()+"'"+" or subUnit "+ logicOp5.getSelectedItem() + filterid6.getText();
        }
        //filter for id, units, start code 
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()+" and subCode like '"+filterid2.getText()+"%'"
                            +" and subId " + logicOp.getSelectedItem() + filterid1.getText();
        }
        //filter for id, units and end code
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()+" and subCode like '%"+filterid3.getText()+"'"
                            +" and  subId " + logicOp.getSelectedItem() + filterid1.getText();
        }
        
        //filter for id units star code end code
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"+filterid2.getText()+"%'"
                    +" and subCode like '%"+filterid3.getText()+"'"+" and subUnit " + logicOp5.getSelectedItem() + filterid6.getText();
        }
        
        //filter for id, units, and start descriptiom
        if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")
                &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()+" and subDes like '"+filterid4.getText()+"%'"
                            +" and  subId " + logicOp.getSelectedItem() + filterid1.getText();
        }
        //filter for id, units, and end descriptiom
        if(!filterid1.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()+" and subDes like '%"+filterid5.getText()+"'"
                            +" and  subId " + logicOp.getSelectedItem() + filterid1.getText();
        }
        //filter for id, units, start and end descriptiom
       if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '"+filterid4.getText()+"%'"
                    +" and subDes like '%"+filterid5.getText()+"'"+" and subUnit " + logicOp5.getSelectedItem() + filterid6.getText();
        }
        ///////////////
       
       //filter for schedule
       if(!filterid7.getText().equals("")){
            filterstring = " where subSched = '"+filterid7.getText()+"'";
        }
       
       //filter for id and schedule
       if(!filterid1.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subSched = '"
                            +filterid7.getText()+"'";
        }
       if(!filterid1.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subSched = '"
                            +filterid7.getText()+"'";
        }
       //code and schedule
     
       //start code
       if(!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" and subSched = '"+filterid7.getText()+"'";
        }
       if(!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '"+filterid2.getText()+"%'"+" or subSched = '"+filterid7.getText()+"'";
        }
       //end code
       if(!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" and subSched = '"+filterid7.getText()+"'";
        }
         
         if(!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subCode like '%"+filterid3.getText()+"'"+" or subSched = '"+filterid7.getText()+"'";
        }
       //description and schedule
       //start schedule
       if(!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subDes like '"+filterid4.getText()+"%'"+" and subSched = '"+filterid7.getText()+"'";
        }
       if(!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subDes like '"+filterid4.getText()+"%'"+" or subSched = '"+filterid7.getText()+"'";
        }
       //end schedule
       if(!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subDes like '%"+filterid5.getText()+"'"+" and subSched = '"+filterid7.getText()+"'";
        }
         
        if(!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subDes like '%"+filterid5.getText()+"'"+" or subSched = '"+filterid7.getText()+"'";
        }
       //unit and schedule
       if(!filterid6.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()+" and subSched = '"+filterid7.getText()+"'";
        }
       if(!filterid6.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()+" or subSched = '"+filterid7.getText()+"'";
        }
       //id, schedule start code
       if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"+filterid2.getText()+"%'"
                           +" and subSched = '"+filterid7.getText()+"'";
        }
       if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"+filterid2.getText()+"%'"
                           +" or subSched = '"+filterid7.getText()+"'";
        }
       //id, schedule end code
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"+filterid3.getText()+"%'"
                           +" and subSched = '"+filterid7.getText()+"'";
        }
        if(!filterid1.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"+filterid3.getText()+"%'"
                           +" or subSched = '"+filterid7.getText()+"'";
        }
       //id, schedule, start code, and code
       if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"+filterid2.getText()+"%'"
                           +" and subCode like '"+filterid3.getText()+"%'"+" and subSched = '"+filterid7.getText()+"'";
        }
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"+filterid2.getText()+"%'"
                           +" or subCode like '"+filterid3.getText()+"%'"
                           +" or subSched = '"+filterid7.getText()+"'";
        }
       //id, schedule, start schedule
        if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '"+filterid4.getText()+"%'"+" and subSched = '"+filterid7.getText()+"'";
        }
       if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subDes like '"+filterid4.getText()+"%'"+" or subSched = '"+filterid7.getText()+"'";
        }
       //id, schedule, end schedule
       if(!filterid1.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '%"+filterid5.getText()+"'"
                           +" and subSched = '"+filterid7.getText()+"'";
        }
         
        if(!filterid1.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subDes like '%"+filterid5.getText()+
                            "'"+" or subSched = '"+filterid7.getText()+"'";
        }
       //id. schedule, start and end schedule
       if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subDes like '"+filterid4.getText()+"%'"+" and subDes like '%"+filterid5.getText()+"'"
                           +" and subSched = '"+filterid7.getText()+"'";
        }
         
        if(!filterid1.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subDes like '"+filterid4.getText()+"%'"+" or subDes like '%"+filterid5.getText()+
                            "'"+" or subSched = '"+filterid7.getText()+"'";
        }
       //id, start code, end code, start adress,end schedule, unit, schedule
       if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" and subCode like '"+filterid2.getText()+"%'"
                           +" and subCode like '"+filterid3.getText()+"%'"+" and subDes like '"+filterid4.getText()+"%'"+" and subDes like '%"+filterid5.getText()+"'"+" and subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()
                           +" and subSched = '"+filterid7.getText()+"'";
        }
        if(!filterid1.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid7.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where subId " + logicOp.getSelectedItem() + filterid1.getText()+" or subCode like '"+filterid2.getText()+"%'"
                           +" or subCode like '"+filterid3.getText()+"%'"+" or subDes like '"+filterid4.getText()+"%'"+" or subDes like '%"+filterid5.getText()+"'"+" or subUnit "+ logicOp5.getSelectedItem() + filterid6.getText()
                           +" or subSched = '"+filterid7.getText()+"'";
        }
        
        DBConnect a = new DBConnect(LoginForm.loguser, LoginForm.logpass,LoginForm.database);
        
        try
        {
            String query = "select * from subjects" + filterstring;
            a.rs = a.st.executeQuery(query);
                    while(a.rs.next())
                    {
                        String id = a.rs.getString("subId");
                        String code = a.rs.getString("subCode"); 
                        String des = a.rs.getString("subDes"); 
                        String unit = a.rs.getString("subunit"); 
                        String sched = a.rs.getString("subSched");
                        String e = a.rs.getString("numOfStud");
                        String[] item = {id,code,des,unit,sched,e};
                        tblmodel.addRow(item);

                    }
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    private void ShowClassList(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable2.getModel();
        tblmodel.setRowCount(0);
        
        DBConnect a = new DBConnect(LoginForm.loguser, LoginForm.logpass,LoginForm.database);
        try
        {
            //String query = "select subjects.subId, subCode, subDes, subUnit, subSched from students, enroll, subjects where students.studid=enroll.studid and enroll.subId=subjects.subId" + filterstring;
            //String query = "select subjects.subId, subCode, subDes, subUnit, subSched from students, enroll, subjects where students.studid="+stid+" and students.studid=enroll.studid and enroll.subId=subjects.subId" + filterstring;
            String query = "select students.studid, studname, studadd, studcrs, studgender,yrlvl from students, enroll, subjects where subjects.subId="+sbId+" and students.studid=enroll.studid and enroll.subId=subjects.subId";
            
            a.rs = a.st.executeQuery(query);
                    while(a.rs.next())
                    {
                        String i = a.rs.getString("studid");
                        String c = a.rs.getString("studname"); 
                        String d = a.rs.getString("studadd"); 
                        String u = a.rs.getString("studcrs"); 
                        String s = a.rs.getString("studgender"); 
                        String y = a.rs.getString("yrlvl"); 
                        
                    
                        String[] item = {i,c,d,u,s,y};
                        tblmodel.addRow(item);

                    }
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        subjects sub = new subjects();
        sub.DelSub(filterstring);
        ShowSubRec();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        subjects sub = new subjects();
        sub.EditSub( Integer.parseInt(subCode.getText()), subDes.getText(), Integer.parseInt(subUnit .getText()),  subSched.getText(), filterstring);
        ShowSubRec();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void filterid1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid1KeyReleased
        ShowSubRec();
    }//GEN-LAST:event_filterid1KeyReleased

    private void filterid2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid2KeyReleased
        ShowSubRec();
    }//GEN-LAST:event_filterid2KeyReleased

    private void filterid3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid3KeyReleased
         ShowSubRec();
    }//GEN-LAST:event_filterid3KeyReleased

    private void filterid4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid4KeyReleased
        ShowSubRec();
    }//GEN-LAST:event_filterid4KeyReleased

    private void filterid7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid7KeyReleased
         ShowSubRec();
    }//GEN-LAST:event_filterid7KeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ShowSubRec();
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int[] selectRow = jTable1.getSelectedRows();
        StudentsForm a = new StudentsForm();
        TeachersForm b = new TeachersForm();
       sbId=(String) jTable1.getValueAt(selectRow[0], 0);
       a.sbid=sbId;
       b.sbid=sbId;
       subId.setText(sbId);
       sbCod=(String) jTable1.getValueAt(selectRow[0], 1);
       subCode.setText(sbCod);
       sbDsc=(String) jTable1.getValueAt(selectRow[0], 2);
       subDes.setText(sbDsc);
       sbUnt=(String) jTable1.getValueAt(selectRow[0], 3);
       subUnit .setText(sbUnt);
       sbSchd=(String) jTable1.getValueAt(selectRow[0], 4);
       subSched.setText(sbSchd);
       ShowClassList();
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void logicOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp1ActionPerformed
        ShowSubRec();
    }//GEN-LAST:event_logicOp1ActionPerformed

    private void logicOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp2ActionPerformed
        ShowSubRec();
    }//GEN-LAST:event_logicOp2ActionPerformed

    private void logicOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp3ActionPerformed
       ShowSubRec();
    }//GEN-LAST:event_logicOp3ActionPerformed

    private void logicOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp4ActionPerformed
        ShowSubRec();
    }//GEN-LAST:event_logicOp4ActionPerformed

    private void logicOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOpActionPerformed
        ShowSubRec();
    }//GEN-LAST:event_logicOpActionPerformed

    private void logicOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp5ActionPerformed
        ShowSubRec();
    }//GEN-LAST:event_logicOp5ActionPerformed

    private void filterid5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid5KeyReleased
         ShowSubRec();
    }//GEN-LAST:event_filterid5KeyReleased

    private void filterid6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid6KeyReleased
         ShowSubRec();
    }//GEN-LAST:event_filterid6KeyReleased

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       ShowSubRec();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filterid1;
    private javax.swing.JTextField filterid2;
    private javax.swing.JTextField filterid3;
    private javax.swing.JTextField filterid4;
    private javax.swing.JTextField filterid5;
    private javax.swing.JTextField filterid6;
    private javax.swing.JTextField filterid7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox logicOp;
    private javax.swing.JComboBox logicOp1;
    private javax.swing.JComboBox logicOp2;
    private javax.swing.JComboBox logicOp3;
    private javax.swing.JComboBox logicOp4;
    private javax.swing.JComboBox logicOp5;
    private javax.swing.JTextField subCode;
    private javax.swing.JTextField subDes;
    private javax.swing.JTextField subId;
    private javax.swing.JTextField subSched;
    private javax.swing.JTextField subUnit;
    // End of variables declaration//GEN-END:variables
}
