/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark Emmanuel Asilum
 */
public class teacheruserform extends javax.swing.JFrame {

    /**
     * Creates new form teacheruserform
     */
    static String tchId, tchName, tchDep, tchAdd, tchCon, tchStat, assignSub;
    String username,tId, temp="3",tes, prelimgrade, midtermgrade, prefigrade, finalgrade, eid;
    int gradeidcnt, gradeid, studId, subId, tmpeid;
    public teacheruserform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        studname = new javax.swing.JTextField();
        studid = new javax.swing.JTextField();
        prelimbox = new javax.swing.JComboBox();
        midtermbox = new javax.swing.JComboBox();
        prefibox = new javax.swing.JComboBox();
        finalbox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Teacher Class List/Grade Encoding Form");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sub ID", "Sub Code", "Sub Desc", "Units", "Schedule", "Students"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stud ID", "Stud Name", "Prelim", "Midterm", "Prefinal", "Final"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Stud ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Stud Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Prelim");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Midterm");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Prefinal");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Final");

        prelimbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        prelimbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prelimboxActionPerformed(evt);
            }
        });

        midtermbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        midtermbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midtermboxActionPerformed(evt);
            }
        });

        prefibox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        prefibox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefiboxActionPerformed(evt);
            }
        });

        finalbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        finalbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalboxActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(studname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(prelimbox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(midtermbox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(prefibox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(finalbox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton1)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prelimbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midtermbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prefibox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prelimboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prelimboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prelimboxActionPerformed

    private void midtermboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midtermboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midtermboxActionPerformed

    private void prefiboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefiboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prefiboxActionPerformed

    private void finalboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalboxActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        assignedSub();
        enrolledStud();
        assignedSub();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        Object cellOfTable = jTable1.getModel().getValueAt(0, 0);
//        subId = String.valueOf(cellOfTable);
        int column = 0;
        int row = jTable1.getSelectedRow();
        String tmp = jTable1.getModel().getValueAt(row, column).toString();
        assignSub = tmp;
        
        
        
        enrolledStud();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int[] selectRow = jTable2.getSelectedRows();
        studid.setText((String) jTable2.getValueAt(selectRow[0], 0));
        studid.setEditable(false);
        studname.setText((String) jTable2.getValueAt(selectRow[0], 1));
        studname.setEditable(false);
    }//GEN-LAST:event_jTable2MouseClicked
    
    public void getEid(){
        DBConnect a = new DBConnect(LoginForm.loguser,LoginForm.logpass,LoginForm.database);
        //select eid from enroll where studid= x and subId =x;
        
        String query = "select eid from enroll where studid="+studid.getText()+" and subId ="+assignSub;
        try{
            a.rs = a.st.executeQuery(query);
            a.rs.next();
            tmpeid=a.rs.getInt(1);
            
        }catch(Exception ex){
            System.out.print("Failed to insert"+ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getEid();
        grades grd = new grades();
        eid = Integer.toString(tmpeid);
        prelimgrade = String.valueOf(prelimbox.getSelectedItem());
        midtermgrade = String.valueOf(midtermbox.getSelectedItem()); 
        prefigrade = String.valueOf(prefibox.getSelectedItem());
        finalgrade = String.valueOf(finalbox.getSelectedItem());
        
        grd.addGrade(prelimgrade, midtermgrade, prefigrade, finalgrade, eid);
        enrolledStud();
         
              
//        test.setText(eid);
//        test1.setText(studid.getText());
//        test2.setText(assignSub);
//        test3.setText(prelimgrade);
//        test4.setText(midtermgrade);
//        test5.setText(prefigrade);
//        test6.setText(finalgrade);
        
       
    }//GEN-LAST:event_jButton1ActionPerformed
   
    public void assignedSub(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        tblmodel.setRowCount(0);
        username = LoginForm.loguser;
        tId = username.replaceAll("[^0-9]", "");
        DBConnect a = new DBConnect(LoginForm.loguser,LoginForm.logpass,LoginForm.database);
        try
        {
            
            String query =  "select subjects.subId, subCode, subDes, subUnit, subSched, numOfStud from assign, subjects,teachers where teachers.teachId="+tId+" and teachers.teachId=assign.teachId and assign.subId=subjects.subId";
            //String query =  "select subjects.subId, subCode, subDes, subUnit, subSched, numOfStud from assign, subjects,teachers where teachers.teachId=1 and teachers.teachId=assign.teachId and assign.subId=subjects.subId";
            a.rs = a.st.executeQuery(query);
                    while(a.rs.next())
                    {
                        String i = a.rs.getString("subId");
                        String c = a.rs.getString("subCode"); 
                        String d = a.rs.getString("subDes"); 
                        String u = a.rs.getString("subUnit"); 
                        String s = a.rs.getString("subSched"); 
                        String n = a.rs.getString("numOfStud");
                        String[] item = {i,c,d,u,s,n};
                        tblmodel.addRow(item);

                    }
        }catch(Exception ex)
        {
            System.out.println("Show assigned records failed"+ex);
        }
    }
    public void enrolledStud(){
        
        DefaultTableModel tblmodel = (DefaultTableModel) jTable2.getModel();
        tblmodel.setRowCount(0);
        
        DBConnect a = new DBConnect(LoginForm.loguser,LoginForm.logpass,LoginForm.database);
        try
        {
            //String query = "select students.studid, studname from students, enroll, subjects where subjects.subId="+assignSub+" and students.studid=enroll.studid and enroll.subId=subjects.subId";
            String query = "select students.studid, students.studname, enroll.studid, grades.prelim, grades.midterm, grades.prefinal, grades.final from enroll join grades on grades.gradeId=enroll.eid join students on students.studid=enroll.studid where enroll.subId="+assignSub;
            
            a.rs = a.st.executeQuery(query);
            while(a.rs.next())
                    {
                        String i = a.rs.getString("studid");
                        String c = a.rs.getString("studname");
                        String p = a.rs.getString("prelim");
                        String m = a.rs.getString("midterm");
                        String pf = a.rs.getString("prefinal");
                        String f = a.rs.getString("final");
                        //String[] item = {p,m};
                        String[] item = {i,c,p,m,pf,f};
//                        String[] item = {i,c};
                        tblmodel.addRow(item);

                    }
           
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacheruserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacheruserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacheruserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacheruserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacheruserform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox finalbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox midtermbox;
    private javax.swing.JComboBox prefibox;
    private javax.swing.JComboBox prelimbox;
    private javax.swing.JTextField studid;
    private javax.swing.JTextField studname;
    // End of variables declaration//GEN-END:variables
}
