/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import static enrollmentsystem.StudentsForm.okcancel;
import static enrollmentsystem.StudentsForm.stid;
import java.awt.Component;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark Emmanuel Asilum
 */
public class TeachersForm extends javax.swing.JFrame {

    /**
     * Creates new form TeachersForm
     */
    //SubjectForm a = new SubjectForm();
    String filterstring = ";";
    static String sbid,tchId, tchName, tchDep, tchAdd, tchCon, tchStat;
    String tmpid, tmpnm, useid,usenm, username;
    int teachCount,i=1;
    String date;
    public TeachersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        teachId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        teachName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        teachDept = new javax.swing.JTextField();
        teachAddr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        teachCont = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teachStat = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filterid = new javax.swing.JTextField();
        logicOp2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logicOp3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        logicOp4 = new javax.swing.JComboBox();
        logicOp5 = new javax.swing.JComboBox();
        logicOp6 = new javax.swing.JComboBox();
        filterid2 = new javax.swing.JTextField();
        filterid3 = new javax.swing.JTextField();
        filterid4 = new javax.swing.JTextField();
        filterid5 = new javax.swing.JTextField();
        filterid6 = new javax.swing.JTextField();
        filterid7 = new javax.swing.JTextField();
        logicOp1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        filterid8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Enter Teacher ID");

        teachId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Teacher Name");

        teachName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Department");

        teachDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachDeptActionPerformed(evt);
            }
        });

        teachAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachAddrActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Address");

        teachCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachContActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter Contact#");

        jLabel6.setText("Enter Status");

        teachStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachStatActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Teacher ID", "Name", "Department", "Address", "Contact", "Status", "Assigned"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel7.setText("Teacher ID");

        filterid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filteridKeyReleased(evt);
            }
        });

        logicOp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Teacher Name");

        jLabel9.setText("Starts");

        jLabel10.setText("Ends");

        logicOp3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Department");

        jLabel12.setText("Address");

        jLabel13.setText("Contact");

        jLabel14.setText("Status");

        logicOp4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp4ActionPerformed(evt);
            }
        });

        logicOp5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp5ActionPerformed(evt);
            }
        });

        logicOp6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        logicOp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp6ActionPerformed(evt);
            }
        });

        filterid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid2KeyReleased(evt);
            }
        });

        filterid3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid3KeyReleased(evt);
            }
        });

        filterid4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid4KeyReleased(evt);
            }
        });

        filterid5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid5KeyReleased(evt);
            }
        });

        filterid6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid6KeyReleased(evt);
            }
        });

        filterid7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid7KeyReleased(evt);
            }
        });

        logicOp1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=", "<>" }));
        logicOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOp1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Starts");

        jLabel16.setText("Ends");

        filterid8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterid8KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logicOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(logicOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(11, 11, 11)
                                        .addComponent(filterid2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(logicOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(filterid3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(filterid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(filterid4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterid5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(filterid8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logicOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logicOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logicOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filterid6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filterid7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(filterid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logicOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logicOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(filterid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logicOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(filterid4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(filterid5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logicOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(filterid6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logicOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(filterid7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logicOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(filterid8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("Assigned Subjects");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SubId", "SubCode", "SubDesc", "SubUnits", "SubSched"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Assign"));

        jButton4.setText("Assign");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teachStat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teachId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(teachName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teachCont, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teachAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(teachDept, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(save)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(162, 162, 162))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(teachId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(teachName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(teachDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(teachAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(teachCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(teachStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delete)
                                .addGap(18, 18, 18)
                                .addComponent(update)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ShowDate(){
        LocalDate now = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM-dd-yyyy");
        date= now.format(formatter);
            
    }
    private void teachIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachIdActionPerformed

    private void teachNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachNameActionPerformed

    private void teachDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachDeptActionPerformed

    private void teachAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachAddrActionPerformed

    private void teachContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachContActionPerformed

    private void teachStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachStatActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        teachers teach = new teachers();
        teach.AddTeach(Integer.parseInt(teachId.getText()), teachName.getText(), teachDept.getText(), teachAddr.getText(), Integer.parseInt(teachCont.getText()), teachStat.getText());
        ShowTeachRec();
        teach.createUserTeach(teachId.getText(), teachName.getText());
        teach.grantPriv(LoginForm.database,teachId.getText(), teachName.getText());
    }//GEN-LAST:event_saveActionPerformed
    private void ShowTeachRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        tblmodel.setRowCount(0);
        
        if(filterid.getText().equals("")||filterid.getText().equals("")||filterid3.getText().equals("")||filterid4.getText().equals("")||
           filterid5.getText().equals("")||filterid6.getText().equals("")||filterid7.getText().equals("")){
            filterstring = ";";
        }
        
        //filter for teachers id
        if(!filterid.getText().equals("")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText();
        }

        //filter for start of name
        if(!filterid2.getText().equals("")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'";
        }

        //filter for end of name
         if(!filterid3.getText().equals("")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'";
        }
         
        //filter for id and start name
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"
                            +filterid2.getText()+"%'";
        }

        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"
                            +filterid2.getText()+"%'";
        }
        //filter for id and end name 
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '%"
                            +filterid3.getText()+"'";
        }

        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '%"
                            +filterid3.getText()+"'";
        }

        //filter for start and end
        if(!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where teachName like '"+filterid.getText()+"%'"+" or teachName like '%"+filterid3.getText()+"'";
        }

        if(!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where teachName like '"+filterid.getText()+"%'"+" and teachName like '%"+filterid3.getText()+"'";
        }


        //filter for id, start and end
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
           &&logicOp2.getSelectedItem().equals("OR")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"
                   +filterid2.getText()+"%'"+" or teachName like '%"+filterid3.getText()+"'";
        }

        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
            &&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"
                            +filterid2.getText()+"%'"+" and teachName like '%"+filterid3.getText()+"'";
        }
        /////
        
        
        
        //////
        
        //filter for start of address
        if(!filterid4.getText().equals("")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'";
        }
        //filter for start of address and id
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '"
                            +filterid4.getText()+"%'";
        }
         if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"
                            +filterid4.getText()+"%'";
        }

        //filter for end of address
         if(!filterid5.getText().equals("")){
            filterstring = " where teachDept like '%"+filterid5.getText()+"'";
        }
        //end of address and id
         if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '%"
                            +filterid5.getText()+"'";
        }
         if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '%"
                            +filterid5.getText()+"'";
        }
         if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
            &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"
                            +filterid4.getText()+"%'"+" and teachDept like '%"+filterid5.getText()+"'";
        }


        //address with logical operator 3
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" and teachDept like '%"+filterid5.getText()+"'";
        }
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" or teachDept like '%"+filterid5.getText()+"'";
        }

        //filter for name and address
        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid2.getText().equals("")
           &&!filterid3.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
           filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" or teachDept like '%"+filterid5.getText()+"'"
                            +" or teachName like '"+filterid2.getText()+"%'"+" or teachName like '%"+filterid3.getText()+"'";
        }

        if(!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid2.getText().equals("")
           &&!filterid3.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
           
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" or teachDept like '%"
                            +filterid5.getText()+"'"+" and teachName like '"+filterid2.getText()+"%'"
                            +" and teachName like '%"+filterid3.getText()+"'";
        }
        
        
        //start of name and start address
        if(!filterid2.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" and teachDept like '"+filterid4.getText()+"%'";
        }
        if(!filterid2.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" or teachDept like '"+filterid4.getText()+"%'";
        }
        //start of name and start address with id
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"
                            +filterid2.getText()+"%'"+" and teachDept like '"+filterid4.getText()+"%'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"
                            +filterid2.getText()+"%'"+" or teachDept like '"+filterid4.getText()+"%'";
        }
        //start name end of address with id
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid5.getText().equals("")
                &&logicOp3.getSelectedItem().equals("AND")&&logicOp2.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                           +" and teachDept like '%"+filterid5.getText()+"'";
        }
        
        
        //end of name and start of address
        if(!filterid3.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" and teachDept like '"+filterid4.getText()+"%'";
        }
        if(!filterid3.getText().equals("")&&!filterid4.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" or teachDept like '"+filterid4.getText()+"%'";
        }
        
         //end of name and start of address with id
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '%"
                            +filterid3.getText()+"'"+" and teachDept like '"+filterid4.getText()+"%'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid4.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '%"
                            +filterid3.getText()+"'"+" or teachDept like '"+filterid4.getText()+"%'";
        }
        
        
        //end of name and end address
        if(!filterid3.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" and teachDept like '%"+filterid5.getText()+"'";
        }
        if(!filterid3.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" or teachDept like '%"+filterid5.getText()+"'";
        }
        //end of name and end address with id
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '%"
                            +filterid3.getText()+"'"+" and teachDept like '%"+filterid5.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '%"+filterid3.getText()+
                            "'"+" or teachDept like '%"+filterid5.getText()+"'";
        }
        
        //end of address and start of name
        if(!filterid2.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" and teachDept like '%"+filterid5.getText()+"'";
        }
        if(!filterid2.getText().equals("")&&!filterid5.getText().equals("")&&logicOp3.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" or teachDept like '%"+filterid5.getText()+"'";
        }
       
        //if naa teachId, name, and address
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
            &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("OR")
            &&logicOp3.getSelectedItem().equals("OR")){
           
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"
                   +filterid2.getText()+"%'"+" or teachName like '%"+filterid3.getText()+"'"+" or teachDept like '"
                   +filterid4.getText()+"%'"+" or teachDept like '%"+filterid5.getText();
        }

        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
           &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
           &&logicOp3.getSelectedItem().equals("AND")){
           
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"
                            +filterid2.getText()+"%'"+" and teachName like '%"+filterid3.getText()+"'"+" and teachDept like '"
                            +filterid4.getText()+"%'"+" and teachDept like '%"+filterid5.getText();
        }

         
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp3.getSelectedItem().equals("OR")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '"
                            +filterid4.getText()+"%'"+" or teachDept like '%"+filterid5.getText()+"'";
        }

        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")
           &&logicOp2.getSelectedItem().equals("AND")){
           filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"
                           +filterid4.getText()+"%'"+" and teachDept like '%"+filterid5.getText()+"'";
        }

        //filter for course
        if(!filterid6.getText().equals("")){
            filterstring = " where teachAddr = '"+filterid6.getText()+"'";
        }

        //filter for id and course
        if(!filterid.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachAddr = '"
                            +filterid6.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachAddr like '"+filterid6.getText()+"'";
        }
        
       
        //name and course
        if(!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" and teachAddr like '"+filterid6.getText()+"'";
        }
        if(!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" and teachAddr like '"+filterid6.getText()+"'";
        }
         if(!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" or teachAddr like '"+filterid6.getText()+"'";
        }
         if(!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" or teachAddr like '"+filterid6.getText()+"'";
        }

         //filter for address and course
        if(!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" and teachAddr like '"+filterid6.getText()+"'";
        }
        if(!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachDept like '%"+filterid5.getText()+"'"+" and teachAddr like '"+filterid6.getText()+"'";
        }
         if(!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" or teachAddr like '"+filterid6.getText()+"'";
        }
         if(!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("OR")){
            filterstring = " where teachDept like '%"+filterid5.getText()+"'"+" or teachAddr like '"+filterid6.getText()+"'";
        }
        //filter for id, course, start name 
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" and teachName like '"+filterid2.getText()+"%'"
                            +" and  teachId " + logicOp1.getSelectedItem() + filterid.getText();
        }
        //filter for id, course and end name
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" and teachName like '%"+filterid3.getText()+"'"
                            +" and  teachId " + logicOp1.getSelectedItem() + filterid.getText();
        }
        
        //filter for id course star name end name
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                    +"and teachName like '%"+filterid3.getText()+"'"+" and teachAddr like '" +filterid6.getText()+"'";
        }
        
        //filter for id, course, and start address
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid6.getText().equals("")&&logicOp3.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" and teachDept like '"+filterid4.getText()+"%'"
                            +" and  teachId " + logicOp1.getSelectedItem() + filterid.getText();
        }
        //filter for id, course, and end address
        if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp2.getSelectedItem().equals("AND")
                &&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" and teachDept like '%"+filterid5.getText()+"'"
                            +" and  teachId " + logicOp1.getSelectedItem() + filterid.getText();
        }
        //filter for id, course, start and end address
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")&&logicOp4.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"+filterid4.getText()+"%'"
                    +"and teachDept like '%"+filterid5.getText()+"'"+" and teachAddr like '" +filterid6.getText()+"'";
        }
       
       //filter for gender
       if(!filterid7.getText().equals("")){
            filterstring = " where teachCont = '"+filterid7.getText()+"'";
        }
       
       //filter for id and gender
       if(!filterid.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachCont like '"
                            +filterid7.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachCont like '"
                            +filterid7.getText()+"'";
        }
       //name and gender
     
       //start name
       if(!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" and teachCont like '"+filterid7.getText()+"'";
        }
       if(!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //end name
       if(!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" and teachCont like '"+filterid7.getText()+"'";
        }
         
         if(!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //adress and gender
       //start address
       if(!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" and teachCont like '"+filterid7.getText()+"'";
        }
       if(!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //end address
       if(!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachDept like '%"+filterid5.getText()+"'"+" and teachCont like '"+filterid7.getText()+"'";
        }
         
        if(!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachDept like '%"+filterid5.getText()+"'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //course and gender
       if(!filterid6.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" and teachCont like '"+filterid7.getText()+"'";
        }
       if(!filterid6.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //id, gender start name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                           +" and teachCont like '"+filterid7.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid2.getText()+"%'"
                           +" or teachCont like '"+filterid7.getText()+"'";
        }
       //id, gender end name
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid3.getText()+"%'"
                           +" and teachCont like '"+filterid7.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid3.getText()+"%'"
                           +" or teachCont like '"+filterid7.getText()+"'";
        }
       //id, gender, start name, and name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")
          &&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                           +" and teachName like '"+filterid3.getText()+"%'"+" and teachCont like '"+filterid7.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid2.getText()+"%'"
                           +" or teachName like '"+filterid3.getText()+"%'"
                           +" or teachCont like '"+filterid7.getText()+"'";
        }
       //id, gender, start address
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"+filterid4.getText()+
                            "%'"+" and teachCont like '"+filterid7.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '"+filterid4.getText()+
                            "%'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //id, gender, end address
       if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '%"+filterid5.getText()+"'"
                           +" and teachCont like '"+filterid7.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '%"+filterid5.getText()+
                            "'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //id. gender, start and end address
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"+filterid4.getText()+" and teachDept like '%"+filterid5.getText()+"'"
                           +" and teachCont like '"+filterid7.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '"+filterid4.getText()+" or teachDept like '%"+filterid5.getText()+
                            "'"+" or teachCont like '"+filterid7.getText()+"'";
        }
       //id, start name, end name, start adress,end address, course, gender
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                           +" and teachName like '"+filterid3.getText()+"%'"+" and teachDept like '"+filterid4.getText()
                           +" and teachDept like '%"+filterid5.getText()+"'"+" and teachAddr like '"+filterid6.getText()
                           +" and teachCont like '"+filterid7.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid7.getText().equals("")&&logicOp5.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid2.getText()+"%'"
                           +" or teachName like '"+filterid3.getText()+"%'"+" or teachDept like '"+filterid4.getText()
                           +" or teachDept like '%"+filterid5.getText()+"'"+" or teachAddr like '"+filterid6.getText()
                           +" or teachCont like '"+filterid7.getText()+"'";
        }
        
        //YEAR LEVEL
        
       //filter for year
        
       if(!filterid8.getText().equals("")){
            filterstring = " where teachStat = '"+ filterid8.getText()+"'";
        }
       
       //filter for id and year
       if(!filterid.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachStat like '"
                            +filterid8.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachStat like '"
                            +filterid8.getText()+"'";
        }
       //name and year
     
       //start name
       if(!filterid2.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" and teachStat like '"+filterid8.getText()+"'";
        }
       if(!filterid2.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '"+filterid2.getText()+"%'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //end name
       if(!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" and teachStat like '"+filterid8.getText()+"'";
        }
         
         if(!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachName like '%"+filterid3.getText()+"'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //adress and year
       //start address
       if(!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" and teachStat like '"+filterid8.getText()+"'";
        }
       if(!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachDept like '"+filterid4.getText()+"%'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //end address
       if(!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachDept like '%"+filterid5.getText()+"'"+" and teachStat like '"+filterid8.getText()+"'";
        }
         
        if(!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachDept like '%"+filterid5.getText()+"'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //course and year
       if(!filterid6.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" and teachStat like '"+filterid8.getText()+"'";
        }
       if(!filterid6.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachAddr like '"+filterid6.getText()+"'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //id, year start name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid8.getText().equals("")
          &&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                           +" and teachStat like '"+filterid8.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid2.getText()+"%'"
                           +" or teachStat like '"+filterid8.getText()+"'";
        }
       //id, year end name
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")
          &&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid3.getText()+"%'"
                           +" and teachStat like '"+filterid8.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid3.getText()+"%'"
                           +" or teachStat like '"+filterid8.getText()+"'";
        }
       //id, year, start name, and name
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")
          &&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                           +" and teachName like '"+filterid3.getText()+"%'"+" and teachStat like '"+filterid8.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid2.getText()+"%'"
                           +" or teachName like '"+filterid3.getText()+"%'"
                           +" or teachStat like '"+filterid8.getText()+"'";
        }
       //id, year, start address
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"+filterid4.getText()+
                            "%'"+" and teachStat like '"+filterid8.getText()+"'";
        }
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '"+filterid4.getText()+
                            "%'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //id, year, end address
       if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '%"+filterid5.getText()+"'"
                           +" and teachStat like '"+filterid8.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '%"+filterid5.getText()+
                            "'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //id. year, start and end address
       if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachDept like '"+filterid4.getText()+"%'"+" and teachDept like '%"+filterid5.getText()+"'"
                           +" and teachStat like '"+filterid8.getText()+"'";
        }
         
        if(!filterid.getText().equals("")&&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachDept like '"+filterid4.getText()+"%'"+" or teachDept like '%"+filterid5.getText()+
                            "'"+" or teachStat like '"+filterid8.getText()+"'";
        }
       //id, start name, end name, start adress,end address, course, year
       if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" and teachName like '"+filterid2.getText()+"%'"
                           +" and teachName like '"+filterid3.getText()+"%'"+" and teachDept like '"+filterid4.getText()
                           +"%'"+" and teachDept like '%"+filterid5.getText()+"'"+" and teachAddr like '"+filterid6.getText()
                           +" and teachStat like '"+filterid8.getText()+"'";
        }
        if(!filterid.getText().equals("")&&!filterid2.getText().equals("")&&!filterid3.getText().equals("")
          &&!filterid4.getText().equals("")&&!filterid5.getText().equals("")&&!filterid6.getText().equals("")
          &&!filterid8.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachId " + logicOp1.getSelectedItem() + filterid.getText()+" or teachName like '"+filterid2.getText()+"%'"
                           +" or teachName like '"+filterid3.getText()+"%'"+" or teachDept like '"+filterid4.getText()+"%'"+" or teachDept like '%"+filterid5.getText()+"'"+" or teachAddr like '"+filterid6.getText()+" or teachStat like '"+filterid8.getText()+"'";
        }
       
        //year and gender
        if(!filterid8.getText().equals("")&&!filterid7.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachStat like '"+ filterid8.getText()+"'"+" and teachCont like '"+filterid7.getText()+"'";
        }
        if(!filterid8.getText().equals("")&&!filterid7.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachStat like '"+ filterid8.getText()+"'"+" or teachCont like '"+filterid7.getText()+"'";
        }
        //year and course
       if(!filterid8.getText().equals("")&&!filterid6.getText().equals("")&&logicOp6.getSelectedItem().equals("AND")){
            filterstring = " where teachStat like '"+ filterid8.getText()+"'"+" and teachAddr like '"+filterid6.getText()+"'";
        }
        if(!filterid8.getText().equals("")&&!filterid6.getText().equals("")&&logicOp6.getSelectedItem().equals("OR")){
            filterstring = " where teachStat like '"+ filterid8.getText()+"'"+" or teachAddr like '"+filterid6.getText()+"'";
        }
        
        DBConnect a = new DBConnect(LoginForm.loguser,LoginForm.logpass,LoginForm.database);
        
        try
        {
            String query = "select * from teachers" + filterstring;
            a.rs = a.st.executeQuery(query);
                    while(a.rs.next())
                    {
                        String id = a.rs.getString("teachId");
                        String name = a.rs.getString("teachName"); 
                        String dept = a.rs.getString("teachDept"); 
                        String addr = a.rs.getString("teachAddr"); 
                        String cont = a.rs.getString("teachCont"); 
                        String stat = a.rs.getString("teachStat"); 
                        String ass = a.rs.getString("assSub");
                        String[] item = {id,name,dept,addr,cont,stat,ass};
                        tblmodel.addRow(item);

                    }
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
         
    }
    
    private void ShowAssignRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable2.getModel();
        tblmodel.setRowCount(0);
        
        DBConnect a = new DBConnect(LoginForm.loguser,LoginForm.logpass,LoginForm.database);
        try
        {
            
            String query =  "select subjects.subId, subCode, subDes, subUnit, subSched from assign, subjects,teachers where teachers.teachId="+tchId+" and teachers.teachId=assign.teachId and assign.subId=subjects.subId;";
            
            a.rs = a.st.executeQuery(query);
                    while(a.rs.next())
                    {
                        String i = a.rs.getString("subId");
                        String c = a.rs.getString("subCode"); 
                        String d = a.rs.getString("subDes"); 
                        String u = a.rs.getString("subUnit"); 
                        String s = a.rs.getString("subSched"); 
                    
                        String[] item = {i,c,d,u,s};
                        tblmodel.addRow(item);

                    }
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        teachers teach = new teachers(); 
        if(teachId.getText().isEmpty()&& teachName.getText().isEmpty()){
            dropEmp();
            teach.DelTeach(filterstring);
        }
        else{
            teach.dropTeach(teachId.getText(), teachName.getText());
            teach.DelTeach(filterstring);
        }
        ShowTeachRec();
    }//GEN-LAST:event_deleteActionPerformed
    private void dropEmp(){
        DBConnect a = new DBConnect(LoginForm.loguser,LoginForm.logpass,LoginForm.database);
        String query1 = "select count(teachId) from teachers";
        try{
            a.rs = a.st.executeQuery(query1);
            a.rs.next();
            teachCount=a.rs.getInt(1);
        }catch(Exception ex){
            System.out.print("Failed to insert"+ex);
        }
        
        try{
            while(teachCount != 0){
                String query2 = "select teachId from teachers where teachId="+i;
                  
                a.rs = a.st.executeQuery(query2);
                while(a.rs.next()){
                    tmpid = a.rs.getString("teachId");
                    useid=tmpid;
                }
                String query5 = "select teachName from teachers where teachId="+i;
                a.rs = a.st.executeQuery(query5);
                while(a.rs.next()){
                    tmpnm = a.rs.getString("teachName");
                    usenm=tmpnm;
                }                    
                username=useid+usenm;
                String query3 = "drop user '"+username+"'@'localhost'";   
                a.st.executeUpdate(query3);                                                          
                teachCount=teachCount-1;
                i=i+1;                    
            }
      
            }catch(Exception ex){
                System.out.print("Failed to insert"+ex);
            } 
    }
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        teachers teach = new teachers();
        teach.EditTeach(teachName.getText(), teachDept.getText(), teachAddr.getText(), Integer.parseInt(teachCont.getText()), teachStat.getText(), filterstring);
        ShowTeachRec();
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int[] selectRow = jTable1.getSelectedRows();
        
       tchId=(String) jTable1.getValueAt(selectRow[0], 0);
       teachId.setText(tchId);
       tchName=(String) jTable1.getValueAt(selectRow[0], 1);
       teachName.setText(tchName);
       tchDep=(String) jTable1.getValueAt(selectRow[0], 2);
       teachDept.setText(tchDep);
       tchAdd=(String) jTable1.getValueAt(selectRow[0], 3);
       teachAddr.setText(tchAdd);
       tchCon=(String) jTable1.getValueAt(selectRow[0], 4);
       teachCont.setText(tchCon);
       tchStat=(String) jTable1.getValueAt(selectRow[0], 5);
       teachStat.setText(tchStat);
       ShowAssignRec();
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       ShowTeachRec();
    }//GEN-LAST:event_formWindowOpened

    private void filteridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filteridKeyReleased
         ShowTeachRec();
    }//GEN-LAST:event_filteridKeyReleased

    private void filterid2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid2KeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_filterid2KeyReleased

    private void filterid3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid3KeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_filterid3KeyReleased

    private void filterid4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid4KeyReleased
       ShowTeachRec();
    }//GEN-LAST:event_filterid4KeyReleased

    private void filterid5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid5KeyReleased
       ShowTeachRec();
    }//GEN-LAST:event_filterid5KeyReleased

    private void filterid6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid6KeyReleased
       ShowTeachRec();
    }//GEN-LAST:event_filterid6KeyReleased

    private void filterid7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid7KeyReleased
       ShowTeachRec();
    }//GEN-LAST:event_filterid7KeyReleased

    private void logicOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp2ActionPerformed
       ShowTeachRec();
    }//GEN-LAST:event_logicOp2ActionPerformed

    private void logicOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp3ActionPerformed
       ShowTeachRec();
    }//GEN-LAST:event_logicOp3ActionPerformed

    private void logicOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp4ActionPerformed
       ShowTeachRec();
    }//GEN-LAST:event_logicOp4ActionPerformed

    private void logicOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp5ActionPerformed
       ShowTeachRec();
    }//GEN-LAST:event_logicOp5ActionPerformed

    private void logicOp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp6ActionPerformed
       ShowTeachRec();
    }//GEN-LAST:event_logicOp6ActionPerformed

    private void logicOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOp1ActionPerformed
        ShowTeachRec();
    }//GEN-LAST:event_logicOp1ActionPerformed

    private void filterid8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterid8KeyReleased
          ShowTeachRec();
    }//GEN-LAST:event_filterid8KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int i = okcancel("Delete SubjectID:"+sbid+" from teachersID: "+tchId);
        if(i==0){
            assign e = new assign();
            e.DeleteAssign(Integer.parseInt(tchId), Integer.parseInt(sbid));
            ShowAssignRec();
            e.UpdateAssSub(Integer.parseInt(tchId));
            JOptionPane.showMessageDialog(this,"Deleted!!!");
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ShowDate();
        int i = okcancel("Assign SubjectID:"+sbid+" to teachersID: "+tchId);
        if(i==0){
            assign e = new assign();
            e.AssignTeach(Integer.parseInt(tchId), Integer.parseInt(sbid), date);
            ShowAssignRec();
            e.UpdateAssSub(Integer.parseInt(tchId));
            JOptionPane.showMessageDialog(this,"Assigned!!!");
            
        }
        
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        ShowTeachRec();
    }//GEN-LAST:event_formWindowGainedFocus
    
    public static int okcancel(String theMessage){
       int result = JOptionPane.showConfirmDialog((Component) null, theMessage,
        "alert", JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JTextField filterid;
    private javax.swing.JTextField filterid2;
    private javax.swing.JTextField filterid3;
    private javax.swing.JTextField filterid4;
    private javax.swing.JTextField filterid5;
    private javax.swing.JTextField filterid6;
    private javax.swing.JTextField filterid7;
    private javax.swing.JTextField filterid8;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox logicOp1;
    private javax.swing.JComboBox logicOp2;
    private javax.swing.JComboBox logicOp3;
    private javax.swing.JComboBox logicOp4;
    private javax.swing.JComboBox logicOp5;
    private javax.swing.JComboBox logicOp6;
    private javax.swing.JButton save;
    private javax.swing.JTextField teachAddr;
    private javax.swing.JTextField teachCont;
    private javax.swing.JTextField teachDept;
    private javax.swing.JTextField teachId;
    private javax.swing.JTextField teachName;
    private javax.swing.JTextField teachStat;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

   
}
